/**
 * Which mods belong to a document, and the bookkeeping that keeps each one running exactly once.
 *
 * On Chrome none of this exists: `chrome.userScripts.register()` hands the browser the match
 * patterns, the frame rule and the timing, and the browser does the matching. The content-script
 * engine has to do that work itself, so it lives here as pure functions the node tests can drive
 * (test/exec-plan.test.ts) rather than inside a content script only a real browser can reach.
 */

import { modMatchesUrl } from '../mods.ts';
import type { Mod } from '../types';

/** The document asking. `topFrame` is how a mod's `allFrames: false` is honoured. */
export interface DocTarget {
  url: string;
  topFrame: boolean;
}

/**
 * The enabled mods that should run in this document, in the order they were saved.
 *
 * Deliberately the same predicate the rest of the app uses (`modMatchesUrl`), so what the Mods list
 * says runs on a page and what actually runs on it cannot drift apart. A mod with neither matches
 * nor include globs is dropped, matching what `userScripts.register()` does with one on Chrome. It
 * rejects it, and a mod that matches nothing has no business running everywhere.
 */
export function modsToRun(mods: Mod[], target: DocTarget): Mod[] {
  if (!target.url) return [];
  return mods.filter(
    (m) =>
      m.enabled &&
      (m.matches.length > 0 || m.includeGlobs.length > 0) &&
      (target.topFrame || m.allFrames) &&
      modMatchesUrl(m, target.url),
  );
}

/**
 * When a mod runs, as a phase the runner can wait for.
 *
 * Safari's `scripting.executeScript` documents `injectImmediately` as effectively always-immediate,
 * so timing cannot be delegated to the browser the way `userScripts.register({runAt})` does it. The
 * runner therefore lands at document_start (the earliest a declared content script can) and holds
 * the later phases back itself:
 *
 *   document_start  now, before the page's own scripts
 *   document_end    DOMContentLoaded, the parser is done, subresources may not be
 *   document_idle   after load, plus a turn, which is what Chrome means by idle
 */
export type RunPhase = 'start' | 'end' | 'idle';

export function phaseFor(runAt: Mod['runAt']): RunPhase {
  return runAt === 'document_start' ? 'start' : runAt === 'document_end' ? 'end' : 'idle';
}

/**
 * The phase that is already over at a given readyState, so a mod claimed late still runs.
 *
 * A content script normally arrives before anything has loaded, but not always: Safari can suspend
 * the background between the script landing and its claim being answered, and the extension can be
 * enabled while pages are already open (`scripting.executeScript` injects the runner into them).
 * Waiting for a DOMContentLoaded that fired ten seconds ago would mean the mod silently never runs,
 * which is the failure mode this exists to prevent.
 */
export function phasesElapsed(readyState: string): RunPhase[] {
  if (readyState === 'complete') return ['start', 'end', 'idle'];
  if (readyState === 'interactive') return ['start', 'end'];
  return ['start'];
}

/**
 * One document's claim, remembered so a repeated claim replays instead of running code twice.
 *
 * The case this is for: the runner asks for its mods, the background is suspended before the reply
 * is delivered, and the runner retries. Without a ledger the retry is a second, independent
 * injection of the same mod into the same page: every `GM_setValue` counted twice, every element
 * the mod appends appended twice. With it, the retry gets the identical grants back and the runner's
 * own per-document guard drops them.
 *
 * Keyed by a document key the runner generates once per document, because that is the only identity
 * that survives both a same-URL reload (which must re-run) and a retry (which must not). Chrome's
 * `documentId` would do, but Safari does not supply one on every message.
 */
export interface ClaimRecord<T> {
  docKey: string;
  tabId: number;
  frameId: number;
  result: T;
  at: number;
}

/** A document's claim is worth remembering for as long as its grants can be used. */
export const LEDGER_TTL_MS = 30 * 60 * 1000;

export class RunLedger<T> {
  private readonly byDoc = new Map<string, ClaimRecord<T>>();
  private readonly ttlMs: number;

  // Assigned in the body, not declared as a parameter property: see the note on GrantTable's
  // constructor in lib/exec/grants.ts.
  constructor(ttlMs: number = LEDGER_TTL_MS) {
    this.ttlMs = ttlMs;
  }

  get size(): number {
    return this.byDoc.size;
  }

  /**
   * A previous claim for this document, if it is still valid.
   *
   * The tab and frame must match as well as the key: a docKey is generated by page-side code, and
   * page-side code is not trusted to be unique or honest. A collision, accidental or deliberate,
   * must not let one document read another's grants.
   */
  replay(docKey: string, sender: { tabId: number; frameId: number }, now: number): T | null {
    const rec = this.byDoc.get(docKey);
    if (!rec) return null;
    if (now - rec.at > this.ttlMs) {
      this.byDoc.delete(docKey);
      return null;
    }
    if (rec.tabId !== sender.tabId || rec.frameId !== sender.frameId) return null;
    return rec.result;
  }

  record(docKey: string, sender: { tabId: number; frameId: number }, result: T, now: number): void {
    this.byDoc.set(docKey, { docKey, tabId: sender.tabId, frameId: sender.frameId, result, at: now });
  }

  forgetFrame(tabId: number, frameId: number): void {
    this.forgetWhere((r) => r.tabId === tabId && r.frameId === frameId);
  }

  forgetTab(tabId: number): void {
    this.forgetWhere((r) => r.tabId === tabId);
  }

  prune(now: number): void {
    this.forgetWhere((r) => now - r.at > this.ttlMs);
  }

  private forgetWhere(pred: (r: ClaimRecord<T>) => boolean): void {
    for (const [key, rec] of this.byDoc) if (pred(rec)) this.byDoc.delete(key);
  }
}
