#!/usr/bin/env node
// Stages everything the compositions load that is not committed under video/:
//
//   assets/fonts/   Jersey 10 and IBM Plex Mono, copied from the repo's own @fontsource packages
//                   (both OFL), so the video uses exactly the faces the extension ships.
//   assets/vendor/  gsap.min.js from video/node_modules, so nothing is fetched at render time.
//   assets/shots/   the README captures the feature beats use, copied from docs/screenshots/.
//   assets/icon.svg the canonical pixel icon, copied from assets/icon.svg.
//   assets/audio/   the chiptune beds, synthesised by scripts/music.mjs, one per set of scene cuts.
//   *.html          the per-aspect-ratio compositions, generated by scripts/variants.mjs.
//
// All of these are generated (index.html is committed too, so Studio opens without a prepare);
// `npm run render` and `npm run render:all` run this first.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const VIDEO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(VIDEO, '..');

function copy(from, to) {
  const src = path.join(ROOT, from);
  const dst = path.join(VIDEO, to);
  if (!fs.existsSync(src)) throw new Error(`missing ${from} (run npm install at the repo root?)`);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

const FS = 'node_modules/@fontsource';
copy(`${FS}/jersey-10/files/jersey-10-latin-400-normal.woff2`, 'assets/fonts/jersey-10-400.woff2');
for (const w of [400, 500, 600, 700]) {
  copy(`${FS}/ibm-plex-mono/files/ibm-plex-mono-latin-${w}-normal.woff2`, `assets/fonts/ibm-plex-mono-${w}.woff2`);
}
copy('video/node_modules/gsap/dist/gsap.min.js', 'assets/vendor/gsap.min.js');
copy('assets/icon.svg', 'assets/icon.svg');

const SHOTS = {
  '12-model-picker.png': 'model-picker.png',
  '11-editing.png': 'editing.png',
  '06-migrate.png': 'migrate.png',
  'ios-ui/after-iphone-390x844-dark.png': 'iphone.png',
  'ios-ui/after-ipad-popover-440x660-dark.png': 'ipad-popover.png',
};
for (const [from, to] of Object.entries(SHOTS)) copy(`docs/screenshots/${from}`, `assets/shots/${to}`);

// The compositions, one per aspect ratio, and a chiptune timed to each set of cuts.
execFileSync(process.execPath, [path.join(VIDEO, 'scripts/variants.mjs')], { stdio: 'inherit' });
const { VARIANTS } = await import('./variants.mjs');
const tracks = new Map(VARIANTS.map((v) => [v.audio, v.cuts]));
for (const [audio, cuts] of tracks) {
  execFileSync(process.execPath, [path.join(VIDEO, 'scripts/music.mjs'), path.join(VIDEO, audio), String(cuts.total), JSON.stringify(cuts)], { stdio: 'inherit' });
}

if (!fs.existsSync(path.join(VIDEO, 'assets/capture/site-before.webp'))) {
  throw new Error('video/assets/capture/ is empty: run `npm run video:capture` at the repo root first');
}
console.log('[prepare] assets staged');
